import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CustomCookiesProvider } from './provider/CustomCookiesProvider'
import { CartProvider } from './provider/CartProvider'
import { IconContext } from 'react-icons'
import { Header } from './header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <div className='bg-red-bean-100'>
          <div className='container mx-auto max-w-6xl'>
            <Header/>
            <div className='p-11'>
              <CustomCookiesProvider>
              <CartProvider>
              {children}
              </CartProvider>
              </CustomCookiesProvider>
          </div>
          </div>
        </div>
        </body>
    </html>
  )
}
